version: "3.1"
services:
  odoo-service:
    user: root
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgresql15-service
    ports:
      - "8069:8069"
    environment:
      - HOST=postgresql15-service
      - USER=odoo
      - PASSWORD=myodoo
      - ODOO_ENV=dev
    volumes:
      - "../capl:/opt/odoo/custom_addons/capl"
      - "../enterprise:/opt/odoo/custom_addons/enterprise"
      - "./.vscode:/opt/odoo/.vscode"
      - "./src/odoo.conf:/etc/odoo/odoo.conf"
    command: bash
    tty: true
  postgresql15-service:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
