version: "3.1"
services:
  web:
    user: root
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mydb:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
      - ODOO_ENV=dev
    volumes:
      - "../fenuasoftware:/opt/odoo/custom_addons/fenuasoftware"
      - "../enterprise:/opt/odoo/custom_addons/enterprise"
      - "./.vscode:/opt/odoo/.vscode"
      - "./src/odoo.conf:/etc/odoo/odoo.conf"
    tty: true
  mydb:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5